name: iap-tutorial
channels:
  - conda-forge
  - defaults
dependencies:
  - c-compiler
  - ipykernel
  - typing-extensions
  - pip
  - python=3.9
  - pip:
      - https://download.pytorch.org/whl/cu116/torch-1.13.0%2Bcu116-cp39-cp39-linux_x86_64.whl#sha256=129d95249fe20ccd83d156323a5e2a6aba83e18841a00ac724e270ad806dd493
      - bilby
      - matplotlib
      - websockets
      - pydantic==1.10
      - lightning==1.8.6
      - pyro-ppl==1.8.0
